[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "refactify"
version = "0.1.0"

[tool.setuptools.packages.find]
include = ["cli*", "codebase*"]

[project.scripts]
refactor = "cli.main:main"